---
title: "Python projet"
author: "Huiyue LI, Jingjing JIANG, Xinyue ZHANG"
date: "2024-03-25"
output: html_document: default
---
# Présentation du projet
Ce projet consiste à extraire des informations sur les offres d'emploi, notamment pour les postes d'alternance situés en Île-de-France.
Notre projet est basé sur le site d'emploi Indeed. Le but est de faciliter la recherche d'emploi, en particulier pour l'étape de postulation. 
Notre objectif est de collecter les emails des ressources humaines (RH) en fonction des informations obtenues,
d'automatiser la rédaction d'email en fonction de la description du poste, de l'email de recrutement et de l'envoi de notre CV pour effectuer la postulation.

```{python}

import time
import random
from selenium import webdriver
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
import re
import pandas as pd
import os
from openai import OpenAI
import resend
```
Pour extraire des informations sur un site dynamique, on utilise selenium qui simuler les actions de l'utilisateur dans le navigateur

```{python}
cService = webdriver.ChromeService(executable_path=r'C:\Users\10144\.wdm\chromedriver-win64\chromedriver.exe')
```

## Fonction pour extrair les liens de tous les offres d'emploi 

Ici, on est dans le domain de data et analyst sur le site d'emploi Indeed, et on peut définir le nombre de page que l'on souhaite y chercher les liens des emplois. Dans notre projet, on vise à extraire les liens d'emploi dans la domaine data et analyst pour 15 pages sur Indeed.

```{python}

def job_links(domains, num_pages):
    links = []
    driver = webdriver.Chrome(service=cService) 
    
    for domain in domains:
        for page in range(1, num_pages + 1):
            start = page * 10
            url = f"https://fr.indeed.com/emplois?q={domain}&l=%C3%8Ele-de-France&sc=0kf%3Ajt(apprenticeship)%3B&start={start}"
            driver.get(url)
            time.sleep(4)

            my_range = [i for i in range(1, 18)]
            for i in my_range:
                xpath_expression = '/html/body/main/div/div[2]/div/div[5]/div/div[1]/div[5]/div/ul/li[{}]/div/div[1]/div/div/div/table[1]/tbody/tr/td/div[1]/h2/a'.format(i)
                elements = driver.find_elements(By.XPATH, xpath_expression)
                if not elements:
                    continue
                link = elements[0].get_attribute('href')
                links.append(link)
    
    driver.quit()
    return links
```
```{python}
links = job_links(['data','analyst'], 15)
```

On vérifie le nombre de lien que l'on obtenu
```{python}
len(links)
```

## Fonction pour trouvez les emails de recrutement à partir des liens de l'offre d'emplois. 
Le résultat affiche à la fois l'email trouvé et le lien original d'où il trouve les emails.

```{python}
def find_emails(links):
  emails_found = []
  driver = webdriver.Chrome(service=cService) 
  for link in links:
      driver.get(link)
      content = driver.page_source 
      soup = BeautifulSoup(content, 'html.parser')
      job_description_element = soup.find('div', id='jobDescriptionText')

      if job_description_element is not None:
          job_description = job_description_element.get_text()
          time.sleep(2)
          email_pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
          emails = re.findall(email_pattern, job_description)
          
          if emails:
              for email in emails:
                  emails_found.append((email, link))
                  
  driver.quit()  
  return emails_found
```

Après obtenir les liens ayant email, on filtre les emails de RH pour recrutement.
```{python}
emails_found = find_emails(links)

emails_rh = [(email, link) for email, link in emails_found if re.search(r'rh|recrutement|hr', email.lower())]

print(emails_rh)
```

## Fonction créée afin d'extraire la description du poste ayant l'email de recrutement.
```{python}
def job_descriptions(email_link):
    job = {}
    driver = webdriver.Chrome(service=cService)
    
    for email, link in email_link:  
        driver.get(link)
        content = driver.page_source 
        soup = BeautifulSoup(content, 'html.parser')
        job_description = soup.find('div', id='jobDescriptionText')
        if job_description:
            job[email] = job_description.text

    driver.quit()
    return job
  
job_description = job_descriptions(emails_rh)
```

Dans cette étape, on enregistre les informations obtenues dans un excel.
```{python}
df = pd.DataFrame(list(job_description.items()), columns=['Email', 'Description'])
result = df.to_excel('job_descriptions.xlsx', index=False)
```
```{python}
os.getcwd() # pour voir où est le fichier excel
```
## Fonction pour automatiser la génération du contenu de l'e-mail de candidature basé sur la description de poste que l'on obtient.
```{python}

client = OpenAI(api_key=" XXX") # remplacer par le api_key utilisé
resend.api_key = "XXX "

def gpt(text):
    role_system = """
    Vous êtes un spécialiste des candidatures à l'emploi et vous vous concentrez sur la création de formats d'e-mails HTML professionnels. Votre tâche consiste à rédiger un courriel de candidature de 200 mots concis et clair pour Jingjing, qui est actuellement étudiante en master de statistiques et d'économétrie à l'Université de Strasbourg. Jingjing possède une solide expertise en économie, en finance et en analyse de données, et a déjà effectué des stages en tant qu'assistante comptable et chargée d'analyse et de reporting. Le courriel doit mettre en évidence son parcours académique, ses expériences professionnelles et sa capacité à travailler à la fois de manière indépendante et en équipe. Le résultat doit être au format HTML, adapté à l'offre d'emploi d'une entreprise française à laquelle Jingjing postule. Le contenu doit être professionnel, en français, et s'adresser directement au responsable de l'embauche ou à l'équipe de recrutement de l'entreprise.
-Objectif : Aider Jingjing à créer une première impression forte avec son courriel de candidature, en mettant en valeur ses qualifications pour un poste qui correspond à sa formation en statistiques, économétrie, économie et finance.
-Format requis : Format HTML, langage professionnel et concis.
    """
    completion = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": role_system},
            {"role": "user", "content": text}
        ]
    )
    return completion.choices[0].message.content
```

## Fonction d'envoi de mails avec pièces jointes à l'aide de l'API Resend.
```{python}


cv_path = "CV_Jingjing_Alternance.pdf"

def send_email(recipient, content, cv_path):
    f = open(cv_path, "rb").read()
    params = {
        "from": "cv@rooster.work",
        "to": recipient,
        "subject": "Candidature d'emploi",
        "html": content,
        "bcc": ["jingjing996131@gmail.com"],
        "attachments": [{"filename": "CV_Jingjing_Alternance.pdf", "content": list(f)}],
    }
    resend.Emails.send(params)

```

## Fonction d'automatisation de l'envoi de mail de candidature,
Selon le résultat on peut vérifier s'il est réussie à envoyer le mail ou pas.
```{python}
file_path = "job_descriptions.xlsx"
df = pd.read_excel(file_path)
cv_path = "CV_Jingjing_Alternance.pdf"

for index, row in df.iterrows():
    recipient = row['Email']
    description = row['Description']
    send_email(recipient, gpt(description), cv_path)
    print(f"Send OK {index}")
```





